add option for api v3
syseleven/syseleven-exporter pull request #58
Opened 2024-09-10 09:25 UTC by gloeckchen404

Adding support for v3 API for Quota and Usage Information

2024-09-10 09:34 UTC, baurmatt requested changes

2024-09-10 09:34 UTC, baurmatt commented on charts/syseleven-exporter-chart/values.yaml
> +  apiversion: v1
Lass uns das einfach hochziehen und nicht unter `openstack` einsortieren. Denn genau genommen ist das keine OpenStack API sondern eine SysEleven eigene

2024-09-10 09:34 UTC, baurmatt commented on cmd/syselevenexporter/syselevenexporter.go
> +	apiVersion		string
Das sieht falsch eingerückt aus. Hast du `go fmt` drüber laufen lassen? :)

2024-09-10 09:53 UTC, gloeckchen404 commented on charts/syseleven-exporter-chart/values.yaml
> +  apiversion: v1
Hab es nach oben gepackt und entsprechend im deployment.yaml  und README angepasst

2024-09-10 09:54 UTC, gloeckchen404 commented on cmd/syselevenexporter/syselevenexporter.go
> +	apiVersion		string
Hab überall nochmal `go fmt ` drüber laufen lassen. :)

2024-09-11 08:11 UTC, baurmatt commented
Thanks for you contribution! :)

2024-09-11 08:12 UTC, merged